import crypto from 'node:crypto';

const ENDPOINT = 'https://dypnsapi.aliyuncs.com/';

const percentEncode = (value: string): string =>
  encodeURIComponent(value).replaceAll('+', '%20').replaceAll('*', '%2A').replaceAll('%7E', '~');

const signRpc = (params: Record<string, string>, secret: string): string => {
  const sorted = Object.keys(params)
    .sort()
    .map((key) => `${percentEncode(key)}=${percentEncode(params[key]!)}`)
    .join('&');

  const stringToSign = `GET&${percentEncode('/')}&${percentEncode(sorted)}`;
  return crypto.createHmac('sha1', `${secret}&`).update(stringToSign).digest('base64');
};

export interface AliyunPnvsCredentials {
  accessKeyId: string;
  accessKeySecret: string;
  schemeName?: string | null;
  signName: string;
  templateCode: string;
}

interface RpcResponse {
  Code?: string;
  Message?: string;
  Model?: {
    VerifyResult?: string;
  };
  Success?: boolean;
}

const callDypnsapi = async (
  action: 'SendSmsVerifyCode' | 'CheckSmsVerifyCode',
  creds: AliyunPnvsCredentials,
  extra: Record<string, string>,
): Promise<RpcResponse> => {
  const query: Record<string, string> = {
    AccessKeyId: creds.accessKeyId,
    Action: action,
    Format: 'JSON',
    RegionId: 'cn-hangzhou',
    SignatureMethod: 'HMAC-SHA1',
    SignatureNonce: crypto.randomUUID(),
    SignatureVersion: '1.0',
    Timestamp: new Date().toISOString().replace(/\.\d{3}Z$/, 'Z'),
    Version: '2017-05-25',
    ...extra,
  };

  query.Signature = signRpc(query, creds.accessKeySecret);

  const url = `${ENDPOINT}?${new URLSearchParams(query).toString()}`;
  const response = await fetch(url, { method: 'GET' });
  return (await response.json()) as RpcResponse;
};

/** SendSmsVerifyCode — uses system-gift sign + template; code generated by PNVS. */
export async function sendSmsVerifyCode(
  creds: AliyunPnvsCredentials,
  phoneNumber: string,
): Promise<void> {
  const extra: Record<string, string> = {
    CodeLength: '6',
    CodeType: '1',
    CountryCode: '86',
    PhoneNumber: phoneNumber,
    SignName: creds.signName,
    TemplateCode: creds.templateCode,
    TemplateParam: JSON.stringify({ code: '##code##', min: '5' }),
    ValidTime: '300',
  };

  if (creds.schemeName?.trim()) {
    extra.SchemeName = creds.schemeName.trim();
  }

  const body = await callDypnsapi('SendSmsVerifyCode', creds, extra);

  if (body.Code !== 'OK' || body.Success === false) {
    console.error('[sms:pnvs] SendSmsVerifyCode failed', {
      code: body.Code,
      message: body.Message,
    });
    throw new Error('SMS_SEND_FAILED');
  }
}

/** CheckSmsVerifyCode — returns true when VerifyResult is PASS. */
export async function checkSmsVerifyCode(
  creds: AliyunPnvsCredentials,
  phoneNumber: string,
  verifyCode: string,
): Promise<boolean> {
  const extra: Record<string, string> = {
    CountryCode: '86',
    PhoneNumber: phoneNumber,
    VerifyCode: verifyCode,
  };

  if (creds.schemeName?.trim()) {
    extra.SchemeName = creds.schemeName.trim();
  }

  const body = await callDypnsapi('CheckSmsVerifyCode', creds, extra);

  if (body.Code !== 'OK' || body.Success === false) {
    console.error('[sms:pnvs] CheckSmsVerifyCode failed', {
      code: body.Code,
      message: body.Message,
    });
    return false;
  }

  return body.Model?.VerifyResult === 'PASS';
}
